import { ReactNode } from "react";
import {
  SiAngular,
  SiBootstrap,
  SiExpress,
  SiFlask,
  SiGiphy,
  SiJest,
  SiMapbox,
  SiNextdotjs,
  SiNodedotjs,
  SiPostgresql,
  SiPrisma,
  SiPython,
  SiReact,
  SiSqlalchemy,
  SiTailwindcss,
  SiTypescript,
  SiZod,
} from "react-icons/si";
import { DaisyUIIcon, JwtIcon, ZustandIcon } from "./custom-icons";
import MotionIcon from "./custom-icons/MotionIcon";

export const ICON_MAP: Record<string, ReactNode> = {
  "React.js": <SiReact />,
  Python: <SiPython />,
  Flask: <SiFlask />,
  SQLAlchemy: <SiSqlalchemy />,
  Bootstrap: <SiBootstrap />,
  "Next.js": <SiNextdotjs />,
  TypeScript: <SiTypescript />,
  "Tailwind CSS": <SiTailwindcss />,
  Jest: <SiJest />,
  Angular: <SiAngular />,
  "Mapbox GL": <SiMapbox />,
  "Giphy API": <SiGiphy />,
  daisyUI: <DaisyUIIcon />,
  JWT: <JwtIcon />,
  Zustand: <ZustandIcon />,
  "Node.js": <SiNodedotjs />,
  Express: <SiExpress />,
  Prisma: <SiPrisma />,
  PostgreSQL: <SiPostgresql />,
  Zod: <SiZod />,
  Motion: <MotionIcon />,
};
